---
- name: Main playbook
  hosts: all
  become: false

  vars_files:
    - vars/default-configs.yaml

  # roles:
  #   - role: gantsign.visual-studio-code

  tasks:
    - name: Install users
      ansible.builtin.import_tasks: tasks/users.yaml
      when: user_name is defined
    - name: Install packages
      ansible.builtin.import_tasks: tasks/packages.yaml
      when: configure_packages
    - name: Set up terminal
      ansible.builtin.import_tasks: tasks/terminal.yaml
      when: configure_terminal
    - name: Set up dotfiles
      ansible.builtin.import_tasks: tasks/dotfiles.yaml
      when: configure_dotfiles
