#!/bin/sh

package_installed()
{
    PACKAGE=$1
    if hash $PACKAGE 2>/dev/null; then
        return 0 # True
    else
        return 1 # False
    fi
}

create_symlink()
{
    FILE=$1
    INSTNAME=$2

    if [ ! -e "$FILE" ]; then
        echo "$FILE does not exist"
        echo "Exiting ..."
        exit
    fi
    
    if [ -e "$INSTNAME" ]; then
        echo "$INSTNAME already exist"
        while true; do
            read -p "Do you wish to overwrite $(basename $INSTNAME)? [y/n]" yn
            case $yn in
                [Yy]* ) echo "Overwriting ...";
                    rm "$INSTNAME";
                    break;;
                [Nn]* ) echo "Exiting ...";
                    exit;;
                * ) echo "Please answer yes or no";;
            esac
        done
    fi

    ln -s "$FILE" "$INSTNAME"
}

BASEDIR=$(dirname $0)

echo "Setting up symlinks"
create_symlink $BASEDIR/bashrc ~/.bashrc
create_symlink $BASEDIR/bash_aliases ~/.bash_aliases
create_symlink $BASEDIR/tmux.conf ~/.tmux.conf





































echo "Not correctly configured"
exit 1

echo 
echo "Testing if python3 is installed"
while ! $(package_installed python3); do
    read -p "Do you with to install python? [y/n]" yn
    case $yn in
        [Yy]* ) echo "Installing ...";
            sudo apt-get install python3;
            sudo apt-get install python3-distutils;;
        [Nn]* ) exit;;
        * ) echo "Please answer yes or no";;
    esac
done

echo
echo "Testing if pip is installed"
while ! $(package_installed pip); do
    read -p "Do you wish to install pip locally? [y/n]" yn
    case $yn in
        [Yy]* ) echo "Installing ..."; 
            curl -s -S https://bootstrap.pypa.io/get-pip.py -o get-pip.py > /dev/null;
            python3 get-pip.py --user;
            rm get-pip.py;;
        [Nn]* ) exit;;
        * ) echo "Please answer yes or no";;
    esac
done

echo
echo "Testing if flake8 is installed"
while ! $(package_installed flake8); do
    read -p "Do you wish to install flake8 locally? [y/n]" yn
    case $yn in
        [Yy]* ) echo "Installing ...";
            pip install flake8 --user;
            break;;
        [Nn]* ) exit;;
        * ) echo "Please answer yes or no";;
    esac
done

echo 
echo "Setting up plugins"
vim -E -v PlugInstall -c q -c q
