#!/bin/sh

package_installed()
{
    PACKAGE=$1
    if hash $PACKAGE 2>/dev/null; then
        return 0 # True
    else
        return 1 # False
    fi
}

create_symlink()
{
    FILE=$1
    INSTDIR=$2
    INSTDIR="${INSTDIR:-$HOME}" 
    # If $INSTDIR is not defined, it takes the default value $HOME

    if [ ! -d $INSTDIR ]; then
        mkdir $INSTDIR
    fi

    if [ -e "$INSTDIR$FILE" ]; then
        echo 
        echo "$FILE already exist"
        while true; do
            read -p "Do you wish to overwrite $FILE? [y/n]" yn
            case $yn in
                [Yy]* ) echo "Overwriting ...";
                    rm "$INSTDIR$FILE";
                    break;;
                [Nn]* ) echo "Exiting ...";
                    exit;;
                * ) echo "Please answer yes or no";;
            esac
        done
    fi

    ln -s "$PWD$FILE" "$INSTDIR$FILE"
}

# Is this necessary?
if [ ! -d $HOME/dotfiles ]; then
    echo "/dotfiles is not located at home"
    echo "Exiting ..."
    exit
fi

cd $HOME/dotfiles/

echo
echo "Setting up symlinks"
cd bashfiles/
create_symlink /.bash_profile
create_symlink /.bash_logout
create_symlink /.bashrc
create_symlink /.bashrc_aliases
cd ../

create_symlink /flake8 ~/.config

cd .vim/
create_symlink /.vimrc
cd ../
create_symlink /.vim

cd tmux/
create_symlink /.tmux.conf
cd ../

echo
echo "Testing if pip is installed"
while ! $(package_installed pip); do
    read -p "Do you wish to install pip locally? [y/n]" yn
    case $yn in
        [Yy]* ) echo "Installing ..."; 
            silent !curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py;
            py get-pip.py --user;
            rm get-pip.py;;
        [Nn]* ) exit;;
        * ) echo "Please answer yes or no";;
    esac
done

echo
echo "Testing if flake8 is installed"
while ! $(package_installed flake8); do
    read -p "Do you wish to install flake8 locally? [y/n]" yn
    case $yn in
        [Yy]* ) echo "Installing ...";
            pip install flake8 --user;;
        [Nn]* ) exit;;
        * ) echo "Please answer yes or no";;
    esac
done

echo 
echo "Setting up plugins"
vim -E -v PlugInstall -c q -c q
