#!/bin/sh

package_installed()
{
    PACKAGE=$1
    if hash $PACKAGE 2>/dev/null; then
        return 0 # True
    else
        return 1 # False
    fi
}

create_symlink()
{
    FILE=$1
    if [ -f "$HOME$FILE" ]; then
        echo "$FILE already exist"
        while true; do
            read -p "Do you wish to overwrite $FILE? [y/n]" yn
            case $yn in
                [Yy]* ) echo "Overwriting ...";
                    rm "$HOME$FILE";
                    ln -s "$HOME/dotfiles$FILE" "$HOME$FILE";
                    break;;
                [Nn]* ) echo "Exiting ...";
                    exit;;
                * ) echo "Please answer yes or no";;
            esac
        done
    else
        echo "Creating symlink"
        ln -s "$HOME/dotfiles$FILE" "$HOME$FILE"
    fi
}

if [ ! -d $HOME/dotfiles ]; then
    echo "/dotfiles is not located at home"
    echo "Exiting ..."
    exit
fi

echo
echo "Setting up symlinks"
create_symlink /.bash_profile
create_symlink /.bash_logout
create_symlink /.bashrc
create_symlink /.bashrc_aliases

