---
- name: Check if Homebrew is installed
  stat:
    path: /home/linuxbrew/.linuxbrew/bin/brew
  register: homebrew

- name: Install Homebrew
  block:
    - name: Ensure sudo, git, and curl is installed
      package:
        name:
          - sudo
          - git
          - curl
        state: present
      become: true

    - name: Get Homebrew
      get_url:
        url: https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
        dest: /tmp/install-brew.sh
        mode: 0777

    - name: Install Homebrew
      command: /tmp/install-brew.sh
  when: not homebrew.stat.exists
