---
- name: Check if ~/.oh-my-zsh/ exist
  ansible.builtin.stat:
    path: ~/.oh-my-zsh/
  register: ohmyzsh_installed
  become_user: "{{ user_name }}"
  become: true

- name: Get oh-my-zsh
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh"
    dest: "/tmp/ohmyzsh-install.sh"
    mode: "0755"
  become_user: "{{ user_name }}"
  when: not ohmyzsh_installed.stat.exists
  become: true

- name: Run installation
  ansible.builtin.command: /tmp/ohmyzsh-install.sh
  when: not ohmyzsh_installed.stat.exists
  changed_when: true
  become_user: "{{ user_name }}"
  become: true
  environment:
    CHSH: "no"

- name: Ensure ~/.oh-my-zsh/ exist
  ansible.builtin.stat:
    path: ~/.oh-my-zsh/
  register: file
  become_user: "{{ user_name }}"
  become: true

- name: Fail if file does not exist
  ansible.builtin.fail:
    msg: "~/.oh-my-zsh/ does not exist"
  when: "not file.stat.exists"
  become_user: "{{ user_name }}"
  become: true
