---
- name: Install gnupg
  package:
    name: gnupg
    state: present
  become: true
  when: (apt_repositories | length) > 0

- name: Add GPG keys
  apt_key:
    url: "{{ item.gpg_url }}"
    state: "{{ item.stat | default('present')}}"
    keyring: "{{ item.keyring | default(omit) }}"
  loop: "{{ apt_repositories }}"
  become: true

- name: Add APT repository
  apt_repository:
    repo: "{{ item.repo }}"
    state: present
  loop: "{{ apt_repositories }}"
  become: true

- name: Upgrade all apt packages
  apt:
    autoclean: true
    update_cache: true
    upgrade: true
  when: upgrade_packages
  become: true

- name: Install packages
  package:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ install_packages }}"
  become: true

- name: install global Pip packages
  pip:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
    version: "{{ item.version | default(omit) }}"
    executable: "{{ item.executable | default(omit) }}"
  loop: "{{ pip_packages }}"

- import_tasks: tasks/install-brew.yaml
  when: configure_homebrew

- name: Install Brew packages
  community.general.homebrew:
    path: "/usr/local/bin:/opt/homebrew/bin:/home/linuxbrew/.linuxbrew/bin"
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ brew_packages }}"
  become_user: "{{ user_name }}"
  become: true

- name: Install go
  include_tasks: tasks/install-go.yaml
  when: install_go
