---
- name: Install dependencies (apt)
  become: true
  ansible.builtin.apt:
    update_cache: true
    name:
      - ca-certificates
      - apt-transport-https
      - gconf2
      - libasound2
      - libgtk2.0-0
      - libxss1
      - libxcb-dri3-0
      - libdrm2
      - libgbm1
      - libxshmfence1
      - acl
    state: present

- name: Add GPG keys
  ansible.builtin.get_url:
    url: "{{ item.gpg_url }}"
    dest: "{{ item.dest }}"
    mode: "0644"
  loop: "{{ apt_repositories }}"
  become: true

- name: Add APT repository
  ansible.builtin.apt_repository:
    repo: "{{ item.repo }}"
    state: present
  loop: "{{ apt_repositories }}"
  become: true

- name: Upgrade all apt packages
  when: upgrade_packages
  become: true
  ansible.builtin.apt:
    autoclean: true
    update_cache: true
    upgrade: true

- name: Install packages
  become: true
  loop: "{{ install_packages }}"
  ansible.builtin.package:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"

- name: Install .deb packages
  become: true
  loop: "{{ deb_packages }}"
  ansible.builtin.apt:
    deb: "{{ item.url }}"

- name: Install global Pip packages
  ansible.builtin.pip:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
    version: "{{ item.version | default(omit) }}"
    executable: "{{ item.executable | default(omit) }}"
  loop: "{{ pip_packages }}"

# - import_tasks: tasks/install-brew.yaml
#   when: configure_homebrew
- name: Install Homebrew
  when: configure_homebrew
  block:
    - name: Check if Homebrew is installed
      ansible.builtin.stat:
        path: /home/linuxbrew/.linuxbrew/bin/brew
      register: homebrew

    - name: Install Homebrew
      when: not homebrew.stat.exists
      block:
        - name: Ensure sudo, git, and curl is installed
          become: true
          ansible.builtin.package:
            name:
              - sudo
              - git
              - curl
            state: present

        - name: Get Homebrew
          ansible.builtin.get_url:
            url: https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
            dest: /tmp/install-brew.sh
            mode: "0777"

        - name: Install Homebrew
          become: true
          become_user: "{{ user_name }}"
          ansible.builtin.command: /tmp/install-brew.sh
          args:
            creates: /home/linuxbrew/.linuxbrew/bin/brew
          environment:
            NONINTERACTIVE: "1"

        - name: Set owner of Homebrew
          become: true
          ansible.builtin.file:
            path: /home/linuxbrew/.linuxbrew/
            state: directory
            recurse: true
            owner: "{{ user_name }}"
            group: "{{ user_group }}"

- name: Tap Brew packages
  community.general.homebrew_tap:
    path: "/usr/local/bin:/opt/homebrew/bin:/home/linuxbrew/.linuxbrew/bin"
    name: "{{ item.tap }}"
    state: 'present'
  loop: "{{ brew_packages }}"
  when: item.tap is defined
  become_user: "{{ user_name }}"
  become: true

- name: Install Brew packages
  community.general.homebrew:
    path: "/usr/local/bin:/opt/homebrew/bin:/home/linuxbrew/.linuxbrew/bin"
    name: "{{ item.name | default(item) }}"
    state: 'present'
  loop: "{{ brew_packages }}"
  become_user: "{{ user_name }}"
  become: true
