---
- name: Install dependencies (apt)
  become: true
  ansible.builtin.apt:
    name:
      - ca-certificates
      - apt-transport-https
      - gconf2
      - libasound2
      - libgtk2.0-0
      - libxss1
      - libxcb-dri3-0
      - libdrm2
      - libgbm1
      - libxshmfence1
    state: present

- name: Add GPG keys
  ansible.builtin.get_url:
    url: "{{ item.gpg_url }}"
    dest: "{{ item.dest }}"
  loop: "{{ apt_repositories }}"
  become: true

- name: Add APT repository
  ansible.builtin.apt_repository:
    repo: "{{ item.repo }}"
    state: present
  loop: "{{ apt_repositories }}"
  become: true

- name: Upgrade all apt packages
  apt:
    autoclean: true
    update_cache: true
    upgrade: true
  when: upgrade_packages
  become: true

- name: Install packages
  package:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ install_packages }}"
  become: true

- name: install global Pip packages
  pip:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
    version: "{{ item.version | default(omit) }}"
    executable: "{{ item.executable | default(omit) }}"
  loop: "{{ pip_packages }}"

# - import_tasks: tasks/install-brew.yaml
#   when: configure_homebrew
- name: Install Homebrew
  block:
    - name: Check if Homebrew is installed
      stat:
        path: /home/linuxbrew/.linuxbrew/bin/brew
      register: homebrew

    - name: Install Homebrew
      block:
        - name: Ensure sudo, git, and curl is installed
          package:
            name:
              - sudo
              - git
              - curl
            state: present
          become: true

        - name: Get Homebrew
          get_url:
            url: https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
            dest: /tmp/install-brew.sh
            mode: 0777

        - name: Install Homebrew
          command: /tmp/install-brew.sh
      when: not homebrew.stat.exists
  when: configure_homebrew

- name: Install Brew packages
  community.general.homebrew:
    path: "/usr/local/bin:/opt/homebrew/bin:/home/linuxbrew/.linuxbrew/bin"
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ brew_packages }}"
  become_user: "{{ user_name }}"
  become: true

# - name: Install go
#   include_tasks: tasks/install-go.yaml
#   when: install_go
