---
- name: Ensure group "{{ user_group }}" exists
  group:
    name: "{{ user_group }}"
    state: present
  become: true

- name: Ensure the user "{{ user_name }}" belongs to "{{ user_group }}"
  user:
    name: "{{ user_name }}"
    shell: /bin/bash
    group: "{{ user_group }}"
    groups: "{{ user_group }}"
  become: true
