---
- name: "Ensure group {{ user_group }}"
  ansible.builtin.group:
    name: "{{ user_group }}"
    state: present
  become: true

- name: "Ensure user belong to group {{ user_name }}"
  ansible.builtin.user:
    name: "{{ user_name }}"
    shell: /bin/bash  # FIXME: always reports "changed", as the shell is later changed to zsh
    group: "{{ user_group }}"
    groups: "{{ user_group }}"
  become: true
