---
# yamllint disable rule:line-length

configure_packages: true
configure_dotfiles: true
configure_terminal: true

configure_homebrew: true

user_name: anders
user_group: sudo
user_shell: /bin/zsh

# Upgrade all packages
upgrade_packages: true

apt_repositories:
  - gpg_url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/trusted.gpg.d/docker-archive-keyring.asc
    repo: deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/docker-archive-keyring.asc] https://download.docker.com/linux/ubuntu impish stable

install_ohmyzsh: true

deb_packages:
  - url: "https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64"

# Packages installed by the package module.
# In 'name' and 'state' format, otherwise use the object as default name
install_packages:
  - sudo
  - git
  - gnupg
  - apt-transport-https
  - ca-certificates
  - lsb-release
  - curl
  - wget
  - vim
  - python3-pip
  - tmux
  - zsh
  - jq
  - containerd.io
  - docker-ce-cli
  - docker-ce

# Packages installed with Pip
# Either in 'name', 'state', 'version' format, or use the object as default name
pip_packages:
  - flake8
  - black
  - virtualenv
  - ruff

# Packages installed with brew
brew_packages:
  - zsh-autosuggestions
  - go
  - node # required by a lot of tools
  - neovim
  - yq
  - kubectl
  - kustomize
  - helm
  - kind
  - tap: derailed/k9s
    name: derailed/k9s/k9s
  - tap: fluxcd/tap
    name: fluxcd/tap/flux
  - direnv
  - tap: int128/kubelogin
    name: int128/kubelogin/kubelogin
  - gh
  - tree
  - act
  - shellcheck # for bash language server

# Packages installed with flatpak
flatpak_packages: # TODO: Add flatpak support
  - chat.rocket.RocketChat
  - com.slack.Slack
  - us.zoom.Zoom

get_files: []
# - url: https://golang.org/dl/go1.17.7.linux-amd64.tar.gz
#   location: ~/go.tar.gz
#   unarchive: true
#   unarchiveLocation: /usr/local
#   check_command: go version

# Location of files either in an array format, or in 'name', 'dest' format.
# Files in array format, are copied to "~/" with the same name.
# If the files are located in a subdirectory on the source, only the name of the file is used
dotfiles:
  - dotfiles/.vimrc
  - dotfiles/.bashrc
  - dotfiles/.bash_custom
  - dotfiles/.zshrc
  - dotfiles/.aliases
  - dotfiles/.tmux.conf
  - name: dotfiles/nvim/
    dest: ~/.config/nvim/

# Configure Git
git_configs:
  - name: core.editor
    value: nvim
  - name: color.ui
    value: auto
  - name: user.email
    value: abbennedsgaard@gmail.com
  - name: user.name
    value: Anders Bennedsgaard
