#!/bin/bash

alias disp="display"
alias la='ls -AF'
alias py="python3"

alias conflicts="git diff --name-only --diff-filter=U"
alias log='git log --all --decorate --oneline --graph'

alias mktar='tar -cvf'
alias untar='tar -xvf'

alias gs='git status'
alias gd='git diff'
alias gf='git fetch --all'

e64() {
    if [ "$2" == "-d" ]; then
        echo -n "$1" | base64 --decode
        echo
    else
        echo -n "$1" | base64
    fi
}

d64() {
    e64 "$1" -d
}
container-ip() {
    if [ $# -eq 0 ]; then
        echo -e "$(docker ps -q | xargs docker inspect -f '{{.Name}}: \t{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}')"
    else    
        docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' "$1"
    fi
}

container-stop () {
    if [ $# -eq 0 ]; then
        docker ps -q | xargs docker stop
    else
        docker stop "$1"
    fi
}

container-enter () {
    if [ $# -ne 1 ]; then
        echo "Only a single argument required"
        exit 1
    fi
    docker exec -it "$1" /bin/bash
}

alias k='kubectl'
# To enable shell completion for the alias
complete -F __start_kubectl k
alias wpo='watch kubectl get pods'
alias wf='watch flux get all -A'
alias fsync='flux reconcile source git flux-system'
alias kga='kubectl api-resources --namespaced --verbs=list -o name | xargs -n 1 kubectl get --ignore-not-found --show-kind'
alias fga='flux get all -A'

